{
 "title": "JMX prometheus exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_info{namespace=\"$namespace\"},pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",namespace=~\"$namespace\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{namespace=~\"$namespace\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_info{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Max {{pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Used  {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"G1 Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"G1 Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"G1 Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"G1 Old Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"G1 Old Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"G1 Old Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"G1 Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"G1 Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"G1 Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=~\"$namespace\", pool=\"Code Cache\",pod_name=~\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pool=\"Code Cache\",pod_name=~\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=~\"$namespace\", pool=\"Code Cache\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM current threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM daemon threads {{pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads  {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "{{gc}}  {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{gc}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "loaded  {{pod_name}}"
    }
   ]
  }
 ]
}