{
 "title": "Node Dashborad",
 "description": "【English version】Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(kube_node_info{node=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "SystemLoad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{node=~\"$hostname\",mode='system'}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU-Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (node)",
     "legendFormat": "{{node}}-Requests"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_1m"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{node=~\"$hostname\"}",
     "legendFormat": "filefd_{{node}}"
    },
    {
     "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "switches_{{node}}"
    }
   ]
  },
  {
   "title": "CPU-Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$hostname\",mode!=\"idle\"}[1m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "System Load Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\"}",
       "legendFormat": "{{node}}_15m"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$hostname\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$hostname\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$hostname\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\"}[30m]))",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory-Allocation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node)",
     "legendFormat": "{{node}}-Requests"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Used"
    }
   ]
  },
  {
   "title": "Memory Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~\"$hostname\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$hostname\"}",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "Swap Utilization%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "{{node}}-Swap%"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "FileSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "FileSystem_Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-(node_filesystem_free_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"})",
       "legendFormat": "{{node}}：{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"} - node_filesystem_avail_bytes{node=~\"$hostname\"})",
       "legendFormat": "free"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\"})",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  { "title": "Disk Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Disk Utilization%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk R/W Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_disk_read_time_seconds_total{node=~\"$hostname\"}[1m]))by (node) / avg(irate(node_disk_reads_completed_total{node=~\"$hostname\"}[1m]))by(node)",
     "legendFormat": "{{node}}-read"
    },
    {
     "expr": "avg(irate(node_disk_write_time_seconds_total{node=~\"$hostname\"}[1m]))by(node) / avg(irate(node_disk_writes_completed_total{node=~\"$hostname\"}[1m]))by(node)",
     "legendFormat": "{{node}}-write"
    }
   ]
  },
  {
   "title": "Disk R/W Bytes",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{node=~\"$hostname\"}[1m])",
     "legendFormat": "{{node}}_{{device}}_Writes"
    }
   ]
  },
  {
   "title": "Disk avgqu-sz",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_weighted_seconds_total{node=~\"$hostname\"}[1m]))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Netrwork", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[1m])*8",
     "legendFormat": "{{node}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[1m])*8",
     "legendFormat": "{{node}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_drop_total[1m]))by(node)",
     "legendFormat": "{{node}}-receive-drop"
    },
    {
     "expr": "avg(irate(node_network_transmit_drop_total[1m]))by(node)",
     "legendFormat": "{{node}}-transmit-drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_errs_total[1m]))by(node)",
     "legendFormat": "{{node}}-receive-errs"
    },
    {
     "expr": "avg(irate(node_network_transmit_errs_total[1m]))by(node)",
     "legendFormat": "{{node}}-transmit-errs"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_TCP_alloc"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } }
 ]
}