{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(nodejs_active_handles_total, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(nodejs_active_handles_total{namespace=\"$namespace\"},pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}[1m]) * 100",
     "legendFormat": "User CPU - {{pod_name}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}[1m]) * 100",
     "legendFormat": "Sys CPU - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{namespace=\"$namespace\",pod_name=\"$pod\"}[1m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}",
     "legendFormat": "Process Memory - {{pod_name}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}",
     "legendFormat": "Heap Total - {{pod_name}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}",
     "legendFormat": "Heap Used - {{pod_name}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}",
     "legendFormat": "Active Handler - {{pod_name}}"
    },
    {
     "expr": "nodejs_active_requests_total{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\"}",
     "legendFormat": "Active Request - {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\",kind=\"minor\"}[1m])",
     "legendFormat": "minor : {{pod_name}}"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\",kind=\"incremental\"}[1m])",
     "legendFormat": "incremental : {{pod_name}}"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\",kind=\"major\"}[1m])",
     "legendFormat": "major : {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\",kind=\"minor\"}[1m])",
     "legendFormat": "minor : {{pod_name}}"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\",kind=\"incremental\"}[1m])",
     "legendFormat": "incremental : {{pod_name}}"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=~\"$namespace.*\",pod_name=~\"$pod.*\",kind=\"major\"}[1m])",
     "legendFormat": "major : {{pod_name}}"
    }
   ]
  }
 ]
}