{
 "title": "1  Node Exporter for Prometheus Dashboard EN v20191102",
 "description": "【English version】Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "2020-05-31T19:44:45.488Z", "to": "2020-05-31T19:54:45.488Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(kube_node_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(kube_node_info{job=~\"$job\"}, node)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(kube_node_info{node=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{node=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node=~\"$hostname\"} / (node_memory_MemTotal_bytes{node=~\"$hostname\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {node=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{node=~\"$hostname\"} / node_memory_SwapTotal_bytes{node=~\"$hostname\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {node=~\"$hostname\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{node=~\"$hostname\"}",
     "legendFormat": "filefd_{{node}}"
    },
    {
     "expr": "irate(node_context_switches_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "switches_{{node}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{node=~\"$hostname\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_1m"
    },
    {
     "expr": "node_load5{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_5m"
    },
    {
     "expr": "node_load15{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_15m"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"system\"}[30m])) by (node)",
     "legendFormat": "{{node}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"user\"}[30m])) by (node)",
     "legendFormat": "{{node}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"iowait\"}[30m])) by (node)",
     "legendFormat": "{{node}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{node}}_Total"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{node}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~\"$hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{node}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{node}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Avaliable"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{node=~\"$hostname\"}[30m]) / irate(node_disk_reads_completed_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{node=~\"$hostname\"}[30m]) / irate(node_disk_writes_completed_total{node=~\"$hostname\"}[30m])",
     "legendFormat": "{{node}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Hardware Temperature(VM may not display the metrics)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{node=~\"$hostname\"}",
     "legendFormat": "{{node}}_{{chip}}_{{sensor}}"
    }
   ]
  }
 ]
}