{
 "title": "Named processes",
 "description": "Process metrics exported by https://github.com/ncabatoff/process-exporter.",
 "tags": [ "OS" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(namedprocess_namegroup_states,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "num processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$node.*\"} ",
     "legendFormat": "{{groupname}} : {{instance}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$node.*\"}[$interval]))by(groupname,instance)",
     "legendFormat": "{{groupname}} : {{instance}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$node.*\",mode=~\"user\"}[$interval]))by(groupname,instance)",
       "legendFormat": "user : {{groupname}} : {{instance}}"
      },
      {
       "expr": "sum(irate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$node.*\",mode=~\"system\"}[$interval]))by(groupname,instance)",
       "legendFormat": "system: {{groupname}} : {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "read bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\"}[$interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "write bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\"}[$interval])",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "resident memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\"}",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "virtual memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\"}",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  }
 ]
}